//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public long Q_ID { get; set; }
        public string Q_Question { get; set; }
        public string Q_ChoiceA { get; set; }
        public string Q_ChoiceB { get; set; }
        public string Q_ChoiceC { get; set; }
        public string Q_ChoiceD { get; set; }
        public string Q_Answer { get; set; }
        public string Q_PicturePath { get; set; }
    }
}
