//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long S_ID { get; set; }
        public string S_FirstName { get; set; }
        public string S_LastName { get; set; }
        public string S_Course { get; set; }
        public string S_Year { get; set; }
        public Nullable<long> S_Score { get; set; }
    }
}
